### ISSUE TITLE
Duplicate actions in the Next header

### ISSUE THREAD

**Issue by abitrolly** [observablehq/feedback#200]
**Describe the bug**

![image](https://user-images.githubusercontent.com/8781107/131728480-2955b3b6-2d3d-4b8a-b89c-a8e4b73c658f.png)

Here you can observe three hearts and two forks.

**To Reproduce**
1. Go to https://observablehq.com/@observablehq/observable-release-notes
2. Click on '...'
3. ???
4. See the screen

**Expected behavior**

~~One dream, one soul,~~
One fork, one heart (preferrably a big one),
One golden glance of what should be.

**Comment by CobusT** [comment]
Thanks for raising this. Even though it could be a bit noisy and cluttered, we made a choice to always keep the menu with all the options, even when we highlight some options as buttons. Marking this as Won't Fix so that we don't set expectations that this will be changed. We appreciate the feedback, though.
