### ISSUE TITLE
Templates: Integrations AWS S3 API Starter - error with @aws-sdk/client-s3 import

### ISSUE THREAD

**Issue by awconway** [observablehq/feedback#275]
**Describe the bug**
[The AWS S3 starter template](https://observablehq.com/@observablehq/aws-s3-api-starter) is throwing this error:

AWS = Error: [Package Error] "@aws-sdk/util-utf8-browser" no dependency version info found. (Imported by "@aws-crypto/sha256-browser").

**To Reproduce**
Just go to the starter template

**Expected behavior**

Code cell AWS = import("https://cdn.skypack.dev/@aws-sdk/client-s3@v3.22.0") should not error even without adding in access key etc (even though the same error persists despite adding this information into a forked notebook).

**Screenshots**

<img width="1348" alt="Screen Shot 2021-10-25 at 9 43 51 AM" src="https://user-images.githubusercontent.com/34257353/138706959-919a29f0-a6e4-4569-8d8c-b86bb4ca0fa8.png">

**Additional context**
I posted this issue in the [Observable Talk](https://talk.observablehq.com/t/templates-integrations-aws-s3-api-starter-error-with-aws-sdk-client-s3-import/5744/4) forum but considering this is an 'official' template I thought reporting here was probably the right way to go.

**Comment by tophtucker** [comment]
This seems to have been finally resolved by v3.39.0 of the AWS SDK, though the conversation continues in [this issue](https://github.com/aws/aws-sdk-js-v3/issues/2810).

It is a little troubling that it broke previously despite having being pinned to a working version. Hoping v3 of the SDK settles down toward something more stable.

There's a lot I could've tried sooner/faster here (instead of freeriding on that issue), but my most acute personal regret is that I should've put a prominent notice at the top of the broken templates as soon as this became an issue. I'm not sure why I didn't. My bad.
