### ISSUE TITLE
Improve SQL Cell table view

### ISSUE THREAD

**Issue by domoritz** [observablehq/feedback#308]
**Is your feature request related to a problem? Please describe.**

The table view requires manual scrolling and looks overall not as polished (e.g. numbers are not right aligned). 

<img width="1192" alt="Screen Shot 2021-12-05 at 14 26 26" src="https://user-images.githubusercontent.com/589034/144760654-a60277a2-8454-4804-8649-6e298d409980.png">

**Describe the solution you'd like**

`Inputs.table` https://observablehq.com/@observablehq/input-table automatically loads more data and looks overall more polished. However, there are some things that are better in the SQL table: row numbers, better displays of nulls, and column sizing. 

<img width="1211" alt="Screen Shot 2021-12-05 at 14 27 21" src="https://user-images.githubusercontent.com/589034/144760691-21b76d9d-2c3c-46fa-bd73-21edc4dbe807.png">

**Comment by domoritz** [comment]
The accuracy of numbers is also a bit excessive in many examples and it looks like the default font is not optimized for viewing numbers. 

<img width="1047" alt="Screen Shot 2021-12-05 at 14 43 14" src="https://user-images.githubusercontent.com/589034/144761190-2591f8b6-f4ba-46fb-9375-3333c018edf8.png">

<img width="1048" alt="Screen Shot 2021-12-05 at 14 42 59" src="https://user-images.githubusercontent.com/589034/144761181-7769f593-3e29-43c1-b77d-c54fc6a8586c.png">

**Comment by mbostock** [comment]
👍 There’s definitely room for improvement in the current SQL cell table design. We’re working on these improvements and it should be out in the near future. I would add the display of dates to the list. Any other specific suggestions you want to make would be welcome!

**Comment by mootari** [comment]
Another problem with the current implementation is, that the result table is not available in embedded notebooks. Instead, only the default Inspector output is shown.

Example: https://observablehq.com/embed/@observablehq/sql-cells?cell=*

In Observable:
![image](https://user-images.githubusercontent.com/322014/146378484-8bcf5acd-66c9-42f7-b399-a84566361b6e.png)

Embed:
![image](https://user-images.githubusercontent.com/322014/146378526-c1370253-79aa-470e-a44d-18ee1d27f592.png)

**Comment by asg017** [comment]
Some other improvements I'd like to see on the SQL cell table view (I can file a new issue if needed):

- **Ability to add warning messages to table**. For example, in Datasette, only [the first 1,000 rows](https://docs.datasette.io/en/stable/settings.html#max-returned-rows) are returned, and I'd like to add a warning that says "results possibly truncated" so that authors know if the data is incomplete.
- **Hooks to add metadata about a query**. For example, adding a message for how long a query took (`1.24 seconds`), which service executed the query, when the query started, etc.
- **Show loading message when querying**. If I have a query I'm iterating on that takes >1 second, I can't tell if the results are stale from a previous run, or if my query is just taking longer than usual. I wish the table would show a loading spinner when a query is taking place, so I know when the query is done loading
- **Ability to hide the results table**. A lot of the time I have some javascript that adds dates + transforms the data a bit, to which I pipe into `Inputs.table` to view. But then, I have two tables: 1 from the SQL cell that's "raw", and 1 for readers to view/interact with. I know I can have two separate cells like `dataRaw` and `data` (and drag the SQL table at the bottom so readers don't see), but doing it over and over again is repetitive.

**Comment by kimmolinna** [comment]
Just a couple of thing.
1) It would be nice to have Line numbers in SQL Cell queries because then it's easier to find line where the error is. 
2) `Inputs.table`is handling integers (big int) nicely but I have to cast all big ints to ints for SQL Cell tables

**Comment by chriszs** [comment]
Enjoying the visual refresh:

<img width="1201" alt="Screen Shot 2022-04-29 at 8 23 00 PM" src="https://user-images.githubusercontent.com/1103467/166083875-5fab860e-4799-44fd-bed8-0bf032164a83.png">

Though the visual inconsistency between the two table styles is even more glaring and I totally second everything @asg017 said, especially the loading indicator, which might actually be harder to see with the new gray background?

**Comment by chriszs** [comment]
To be honest, I'm not sure why one takes a pagination approach and the other an infinite scroll approach. It's not like the SQL one is fetching more results from a server.

**Comment by CobusT** [comment]
Many of the issues mentioned here have now been fixed:
☑️ Pagination through scrolling 
☑️ Numbers right aligned
☑️ Better handling of number of digits 
☑️ Better font for numbers (and in general for tabled results)
☑️ Indicator of data loading (spinner at the right of the cell editor)
☑️ Ability to hide the table (through the 👁️ icon in the cell editor menu)

Not done yet:
- You cannot view the table in the embedded view (also reported in #468)
- Line numbers in the SQL cell editor (not really related to this issue)
- Not sure about the BigInts...

**Comment by mbostock** [comment]
BigInt is now supported, although I notice that we aren’t doing localized formatting for them yet. We’ll fix that.

<img width="1216" alt="Screen Shot 2022-11-02 at 6 47 16 AM" src="https://user-images.githubusercontent.com/230541/199505967-e0f65df0-cc49-48a5-a05f-7d4f1673fcf3.png">

**Comment by mbostock** [comment]
Number formatting is also improved in https://github.com/observablehq/feedback/issues/308#issuecomment-986288618:

<img width="1210" alt="Screen Shot 2022-11-02 at 6 56 03 AM" src="https://user-images.githubusercontent.com/230541/199507978-8448729c-8128-465b-8579-8d50c0181ba5.png">

**Comment by domoritz** [comment]
Ahh, I see. I really need to make the observable client a proper module with tests and move it out of a notebook. @enjalot and I talked about it last week.
