### ISSUE TITLE
collections missing after changing my username

### ISSUE THREAD

**Issue by flurrux** [observablehq/feedback#396]
hey guys, 

i have two observablehq accounts, one registered with google and another one registered with github, which turned into my main account.  
i wanted to transfer my username from the google account to the github account, so what i did was

- in my google account, change my username from "flurrux" to "flurrux-legacy"
- in my github account, change my username from "5dd639cc38411a53" to the now available "flurrux"

this worked fine, except that all of my collections are now missing (i had about 6 or 7) and when i try to create a new collection, i get the following error: 

![observable error message](https://user-images.githubusercontent.com/40806446/161384394-8915f7aa-9bd3-4b9b-a725-2c27f44557ee.jpg)

chrome logs a 403 error

![console error](https://user-images.githubusercontent.com/40806446/161384489-aa5828ce-d2de-4d78-8264-85d7566e94d8.jpg)

i was hoping this error would go away after some time, but it still persists after several days.

**Comment by CobusT** [comment]
I am going to have our support team look into this on Monday to see how we can get you going again. I don't think your collections are gone, but your account is in a strange state and needs some attention.

You didn't do anything wrong, btw, but the way you tried to switch auth provider (from google to GitHub), although intuitive, should not have worked... When changing a username, we keep the old name active and aliased to the same account so that imports, public notebooks etc. that were referencing @flurrux would still work.
When you created your new GitHub account and renamed it to flurrux, it should not have allowed that and should have shown you an error that you could not use that name.

My theory is that when you are logging in with GitHub now, you are landing in some strange state where we have two accounts with the same name 'flurrux', which is causing these errors. This is something the support team will be able to address. 

Please look out for an email on Monday from them.

**Comment by flurrux** [comment]
thanks @CobusT, i got the email and my collections are now visible and working as usual.  
thank you so much for your help!
