### ISSUE TITLE
Unable to save changes after duplicating a named cell

### ISSUE THREAD

**Issue by piecesofuk** [observablehq/feedback#420]
**Describe the bug**
If I duplicate a named cell I get an error message "Unable to save changes" and the notebook will no longer save any future edits

**To Reproduce**
1. Create a blank notebook
2. add a new javascript cell with for example a = 1
3. duplicate this cell, new cell contains a1 = 1
4. "Unable to save changes" is displayed

**Expected behavior**
The notebook shouldn't error

**Screenshots**
![error](https://user-images.githubusercontent.com/578197/168466799-202eca27-d94e-437e-b75f-0848b4565dcb.png)
![error1](https://user-images.githubusercontent.com/578197/168466806-d9691206-c6f4-4d26-ae50-cf5058126f86.png)

**Desktop (please complete the following information):**
Tested in Firefox 99 on Windows 10; Chrome 92 on a Chromebook and Chrome 100 on a Chromebook

**Comment by mbostock** [comment]
Thanks for the report. We are investigating.

**Comment by mbostock** [comment]
We are deploying a fix for this issue. Thank you again for the report!

It’s possible that you may continue to see “unable to save changes” errors on notebooks that previously exhibited this bug after duplicating a cell. That is because Observable is trying to re-apply invalid stashed changes in your browser local storage.

If you are okay losing your unsaved changes, you can fix this by clearing your browser’s local storage for observablehq.com. In Chrome, go to Settings > Privacy and security > Cookies and other site data > See all cookies and site data. In the Search cookies field, enter “observablehq.com”, then click on the observablehq.com entry, then click on the X next to local storage. Then reload the notebook that is unable to save.

If you wish to recover your unsaved changes, you can copy the contents of your cells before deleting your browser’s local storage, and then paste the cells back in after deleting and reloading.

**Comment by piecesofuk** [comment]
Thanks for the update. Seems to be working okay now.
