### ISSUE TITLE
Improve user experience on “Published”/“Unlisted” notebooks

### ISSUE THREAD

**Issue by galopin** [observablehq/feedback#551]
**Is your feature request related to a problem? Please describe.**

> This notebook is read-only until you make it public, or upgrade your account to work in private.

I would like to point out an incongruity when opening any “Published”/“Unlisted” notebook I created before the October 2022 platform change: It is marked as read-only and there is no way to interact with it even though I am the original author — Tinker mode is not even accessible via the “View” menu which is a shame.

Whereas I am completely free to tinker with the very same notebook and make any changes I want when I open it in an incognito tab without authenticating myself. Whisky Tango Foxtrot!?

**Describe the solution you'd like**

A read-only notebook should not prevent an authenticated owner from performing (temporary) changes on any cell. Also, please reinstate Tinker mode in that specific case. I hope you can fix this in the near future…

**Describe alternatives you've considered**

Granted, I can make the “Published”/“Unlisted” notebook public in order to avoid this annoying behavior.

**Additional context**

The above user experience should be the one for notebooks marked as  “Only you”.

BTW, Tinker mode is buried deep within the “View” menu: Why not make it a promoted action button, or even better, a first-level item in the sidebar?

**Comment by Fil** [comment]
Hello fellow human being, please take a minute and imagine that another human is receiving your feedback and has to process it emotionally. It should be possible to convey your message in a convivial and less alienating way. Thank you.

**Comment by galopin** [comment]
I am sorry that my feedback was perceived in this way. My intention was only to point out a glaring inconsistency which, I admit, irritated me somewhat. I only wish that this incomprehensible difference in treatment could be corrected. In retrospect, I realize that the tone may shock or challenge but there is no animosity of any kind here. (Only grumpiness I confess; admittedly, it can be difficult to distinguish.) My apologies.

**Comment by galopin** [comment]
Maybe I'm wrong, but with more hindsight, I feel like this issue also affects any tier user (Free, Pro, or Enterprise) who created Observable notebooks before the October 2022 platform change. I'm not Pro so I was sort of misled about the difference in treatment. Consequently, I will rephrase (again) the title of this ticket…

**Comment by CobusT** [comment]
Hi @galopin 

Thanks for sharing your experience.

I would like to offer some context around the behavior differences you are seeing. When you are in tinker mode, your changes are not saved to the notebook, and it is just you tinkering in the browser. This is different from how it used to work for notebook owners making changes to their published notebooks. They were actually not in tinker mode, but were actually saving further (private, unpublished) versions of the published notebook. 

That is the reason why, in order to edit the published notebook now, the notebook owner needs to make the notebook public (not published), which is how the notebook model works after the changes in October last year. And that is why the message at the top of published notebooks mention to either change the published notebook to public, or to make it private (which requires a Pro account). 

I noticed that you said an alternate solution would be to just make the notebook public. May I ask why you are thinking of that as an alternative solution rather than the intended path? We did not want to just change all the published notebooks to public in October, but thought of giving users the choice to change their notebooks over to the new model.

**Comment by galopin** [comment]
Hi @CobusT 

> I would like to offer some context around the behavior differences you are seeing. 

What I'm trying to point out is that any Observable user has the possibility to make *temporary* changes on a notebook made public according to the old workflow while his own creator is now *deprived* of this privilege!?

This situation can also be summarized as follows:

1. I can make any temporary changes on any published/unlisted/public notebook I did not create
2. I cannot make any temporary changes on a notebook that I created and published in the previous model

Why do I insist so much on the ability to make temporary changes? Because this is my preferred method for preparing a fork. It seems more natural to me.

I don't dispute the presence of the current message, nor the choices offered, nor the fact that the notebook is in read-only mode. Only the fact that it is impossible for an author to make any temporary change: it is absurd and contrary to the spirit of the platform :-/

I mentioned the Tinker mode because I used it a lot initially and find it useful. (When you are tinkering, you are given the option of turning those temporary changes into a fork.) I don't understand why this feature isn't highlighted more. Perhaps I should have avoided mentioning it because it obviously pollutes the debate I am trying to raise...

> I noticed that you said an alternate solution would be to just make the notebook public. May I ask why you are thinking of that as an alternative solution rather than the intended path? We did not want to just change all the published notebooks to public in October, but thought of giving users the choice to change their notebooks over to the new model.

Because there is actually no point into turning some unlisted notebooks into public. Unlisted notebooks are ideal for submitting suggestions and elaborating proofs of concept without cluttering/polluting the Observable user space. (I miss that functionality only available to Pro users.)

Also I welcome the fact that not all published/unlisted notebooks have been switched automatically to the new model. It was the right decision. But performing it one-by-one on every notebook you own is *a chore*. At the user interface level, it is not currently possible for an author to select multiple notebooks to switch to the new model.

To be quite candid, I have done this for some notebooks but not all ;-)

**Comment by CobusT** [comment]
Thank you for this explanation. One clarification on your point #2. 
Pro users can actually still make saved changes to their published notebooks (which effectively creates private versions of the notebook), but they cannot republish those changes (they need to make the notebook public to do that). Here is the message they see when opening a legacy Published notebook and starting to edit it:

<img width="945" alt="image" src="https://user-images.githubusercontent.com/10869236/223440773-727b9657-f2ca-4305-b6b2-8e2aab2b2423.png">

And the reason Free users are not able to do the same is that Free users are not allowed to create private notebooks...

I do think that **Tinker mode** is relevant as part of the discussion, since Tinker mode would enable the Free user to make those temporary edits and then fork the notebook (to a new public notebook).

**Comment by galopin** [comment]
With the introduction of [Observable 2.0](https://observablehq.com/release-notes/2024-02-15-observable-2-0) yesterday, my workspace has been migrated to the new free Starter tier. I can now work in private and even collaborate with others! All my grievances expressed in this thread are now null and void. Huzza!

**Comment by CobusT** [comment]
That is great to hear. It has been a journey to arrive here, but we are very happy with this new direction. Time to close this issue? :-)

**Comment by galopin** [comment]
I think indeed we can close this long-standing issue.

🤔 I hope that you'll continue to improve the notebooks and that they won't be abandoned for the sake of the framework alone. What I like about Observable notebooks is that they don't require a full development environment and all the hassles that come with it.

BTW, among the inherent limitations of notebooks, Mike Bostock mentions:

> Always-visible editor chrome

Why not provide a toggle to hide the always visible editor chrome for show and tell?

**Comment by CobusT** [comment]
Thanks. BTW, I like using the /embed view for show and tell, e.g:
`https://observablehq.com/embed/03aeb39c5258de94?cell=*`
