### ISSUE TITLE
(docs) Wrong component name "range" indicated in the "Learn how to write and run JavaScript on Observable" tutorial.

### ISSUE THREAD

**Issue by kamweti** [observablehq/feedback#606]
**Describe the bug**
A component "range" is not found when you search  for it.

Step 3 of 5 in https://observablehq.com/guide/first-steps

**To Reproduce**
* Go to the First steps with Observable page https://observablehq.com/guide/first-steps
* Complete the first 2 steps in the tutorial
* In the third step the user is required to search and add component named "range" but its not returned in result

**Expected behavior**
* Return the appropriate component in search results
* range component has since been renamed to "slider" (see screeshot below)

**Screenshots**
![image](https://github.com/observablehq/feedback/assets/118835/30f50a1b-f2bb-4deb-8c28-6e2edff8d28d)

![image](https://github.com/observablehq/feedback/assets/118835/a491f879-f70c-4f30-bc2c-50c427418014)

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Comment by tophtucker** [comment]
Hi @kamweti; thanks for reporting this.

We recently tried changing the name of the item in the menu from “Range” to “Slider”, because, colloquially, we more often hear people talk about sliders. But we were inconsistent; as you noticed, parts of the Quick Guides and documentation were never updated. 

We’ve now changed the name of the menu back to “Range”, which matches our [Inputs library](https://observablehq.com/@observablehq/input-range) and the [standard HTML term](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range). The description now mentions “slider”, so either term will work if you type to filter.

<img src="https://github.com/observablehq/feedback/assets/841829/e6a4bb52-35c4-4167-ad54-4731359cb5ba" width="300"/>
