### ISSUE TITLE
schedules: currentUser is only available in unpublished team notebooks

### ISSUE THREAD

**Issue by nachocab** [observablehq/feedback#607]
The [documentation for the schedules](https://observablehq.com/documentation/notebooks/schedules#you-can-run-code-differently-in-the-scheduler) says that it's possible to detect if it's running in the cloud or not, but if I access `currentUser.login` I get an error: `RuntimeError: currentUser is only available in unpublished team notebooks`

**Comment by CobusT** [comment]
We plan on having `currentUser` available in individual workspaces soon. It is currently only available in team workspaces.

**Comment by tophtucker** [comment]
Oddly, it _will_ still work currently; it’ll error in the notebook in the browser, and not in the scheduled run in the cloud, because the scheduler service defines currentUser. But yes, as Cobus said, it’s confusing currently and we’re fixing it. (currentUser has historically been just for private team-workspace notebooks.)

**Comment by tophtucker** [comment]
You can now access currentUser in any private notebook. (We eliminated the distinction between “individual” and “team-owned” notebooks; they’re all notebooks in a workspace. In the individual case, the workspace just has one member.)
