### ISSUE TITLE
Possible bug with non-updating cell value upon evaluation

### ISSUE THREAD

**Issue by yurivish** [observablehq/feedback#61]
**Describe the bug**

While working on a two-way `bind` between visualizations, I made an [example notebook](https://observablehq.com/d/4305a524603168da) which has some surprising behavior wrt. `viewof` cells.

I'm not sure if I'm mis-using `bind` here, but the surprising behavior is that a cell takes on a new value when re-evaluated, but only if re-evaluated after being removed and created again.

**To Reproduce**

1. Click on `click me a`. The value of a in the cell below will still be `42`.
2. Re-run the `a` cell. Still `42`.
3. Delete the cell, and add a new cell with the value `a`. Now it shows the new value of `a`.

**Expected behavior**
Re-evaluating `a` should give the same result as deleting and re-creating the cell.

**Screenshots**

![image](https://user-images.githubusercontent.com/114388/112561920-8e867580-8dac-11eb-9efa-cc246b11be95.png)

**Desktop (please complete the following information):**
macOS with Chrome Version 89.0.4389.90 (Official Build) (x86_64)

**Comment by mbostock** [comment]
This is a bug in your `viewof a` definition. If the value changes, you should emit an *input* event, e.g.,

```js
ret.addEventListener('click', () => {
  set(viewof input, Math.random());
  ret.dispatchEvent(new Event("input"));
});
```

Re-evaluating `a` does not query the view for its new value, since it was previously-evaluated. Removing the reference to `a` garbage collects the associated generator, since no other cell references it, and variables are evaluated lazily. So when you restore a reference to `a`, the corresponding generator (Generators.input) is re-initialized, querying the latest value of the view. But the bug is in the view: if its value changes, it should emit an *input* event, and if it doesn’t, there’s no guarantee on what value is visible to other cells.

**Comment by yurivish** [comment]
Thank you Mike, your comments helped me understand how to best use `bind` (I hope I have it right now!) — there's no need to re-propagate the state held in `input` into all of the readers/writers; anybody interested in the value should read it from `input`. And the "subscribers" should refer to `viewof input.value` rather than `input` to avoid unnecessary re-evaluations.

I had missed the lack of symmetry underscored by this paragraph of the documentation:

> When the target emits a type-appropriate event, the target’s type-appropriate value will be applied to the source and a type-appropriate event will be dispatched on the source; when the source emits a type-appropriate event, the source’s type-appropriate value will be applied to the target, but no event will be dispatched, avoiding an infinite loop.
