### ISSUE TITLE
Posting a complaint here (as a last resort)

### ISSUE THREAD

**Issue by oksure** [observablehq/feedback#629]
Hi,

I have been a loyal Observable paid user (annual) only 3-4 months ago. I have been using Observable as an educational tool in my class to teach d3 and visualization in data science.

I recently learned that you changed the pricing structure last month. I also learned that I got bumped down to the free tier without any explanation. While I understand it is important to pivot multiple times as a startup quickly, it was a big disappointment.

I also submitted a request for the educational discount but never heard back. https://observablehq.com/@educators-network/contact-edu

A couple of months ago, I filed a bug report here, and I got a reply fairly quickly. https://github.com/observablehq/feedback/issues/601

So I am posting my complaint here as a last resort. If I don't hear from you about this, I won't bug you about this any further.

Thanks for the great work. I truly appreciate and admire your great work.

HP

**Comment by ananya-roy** [comment]
Hi HP,

We are sorry to hear that you haven’t been hearing back from us. We sent an email regarding your tier change on Feb 15, and an email with an edu discount coupon on Feb 28.  The first email went to the gmail address associated with your account and the second was sent to the edu email in your discount request form. We would really like to understand and debug why our emails are not reaching you. Please write to us at [support@observablehq.com](mailto:support@observablehq.com) so that we can figure this out and get you set up with a new discount coupon for your class. 

Thanks,
Ananya

**Comment by ananya-roy** [comment]
Also, we can understand how unexpected and confusing your tier change must have felt if our email explaining the change didn't reach you. The reason we migrated your account to the free tier was because you now get all the benefits and functionality of the older Pro Individual tier for free in the new [Starter tier](https://observablehq.com/pricing). We are happy to answer any questions you may have about the new tiers when we connect.

Thanks,
Ananya

**Comment by oksure** [comment]
Hi Ananya,

Thank you for your prompt response and for addressing my concerns. I appreciate you taking the time to explain the recent changes to the pricing structure and how the older Pro tier features are now included in the new Starter tier.

While I have some concerns about the value I received for the annual subscription I paid for last October, given the pricing changes in February (thus, I received 1/3 the value of what I paid for), I recognize that business decisions sometimes need to be made.

I just hoped that my feedback regarding the pricing structure and its impact on existing subscribers would reach the business planning team at Observable. I really think the platform and the product are fantastic game changers, as I believe they drastically lower the barriers to creating d3-based visualizations. I evangelize them in my vis classes.

I will follow up with you via the provided email address to discuss the educational discount further. (The new Pro tier is a bit prohibitive, so I hope the educational discount is helpful.) Again, Thank you for your quick response and commitment to addressing user concerns. Please keep up the great work!

Thanks,

HP

P.S. I will go ahead and close this issue.
