### ISSUE TITLE
Cell are not loading

### ISSUE THREAD

**Issue by LaoTzunami** [observablehq/feedback#632]
**Describe the bug**
cells are not loading or running

**To Reproduce**
open most notebooks and the cells will not load

**Expected behavior**

**Screenshots**
![image](https://github.com/observablehq/feedback/assets/96704669/11b96b0d-af3a-47b6-abc7-8ac64ededf79)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Comment by tophtucker** [comment]
This can happen when the worker hangs; see “[How to crash Observable](https://observablehq.com/@tophtucker/how-to-crash-observable)” for some examples and discussion. One subtlety is that, because Chrome shares threads across tabs (and even windows, maybe?), a crash in a notebook in one tab can crash _all_ open notebooks. You can use the Chrome task manager to select any Observable (or observableusercontent.com) tabs and “End Process”, or you can try restarting Chrome.

If it keeps crashing, there may be an infinite loop or something very memory-intensive in one of the notebooks you’re opening that keeps crashing the worker anew. You can view the notebook in “safe mode” by appending /safe to the URL, and restore an older version that doesn’t crash.

(Notebooks seem to be loading fine for me, but if that doesn’t work for you, please do let us know — there may be another issue!)

**Comment by mootari** [comment]
@LaoTzunami Are you still experiencing problems? If yes, do you see the same issues in a private/incognito window?
