### ISSUE TITLE
Editor contents in Next load delayed or incomplete (partially blank)

### ISSUE THREAD

**Issue by mootari** [observablehq/feedback#84]
**Describe the bug**
The CodeMirror editors in Next appear to apply some sort of lazy loading/rendering to their contents. I've frequently run into situations where, after scrolling downwards, an editor had the correct height, but was almost completely empty.

In addition, the lazy loading makes it impossible to reliably search a whole page for text occurences.

**To Reproduce**
Demonstration of the differences through the browser's text search:
1. Open https://observablehq.com/@mcmcclur/d3-graphviz-with-mathjax/safe?ui=classic
2. Searching the page for "texit" will show a result count of 4.
3. Open https://observablehq.com/@mcmcclur/d3-graphviz-with-mathjax/safe?ui=next
4. Searching the page for "texit" will show a result count of 3.
5. Close browser search.
6. Scroll to end of page.
7. Searching the page for "texit" will now show a result count of 4.

**Expected behavior**
Editor contents are loaded immediately, so that they are searchable and rendering delays are avoided.

**Browser:**
Chrome 89 on MacOS 10.13.6

**Comment by jrus** [comment]
Also happens in Safari. Clicking into the apparently empty cell editor will typically cause the code to render.

**Comment by mootari** [comment]
Example (previous actions: scrolling down to add a cell, then scrolling back up):
![image](https://user-images.githubusercontent.com/322014/116797563-4531f000-aae7-11eb-9540-fe2bdc6dca92.png)

Editor contents load after resizing the viewport or clicking into the cell.

**Comment by mootari** [comment]
I still encounter this problem almost daily. Would be nice to get some feedback from the team here.

Also, please feel free to move this issue to https://github.com/observablehq/preview-feedback

**Comment by mootari** [comment]
Related with respect to browser search: https://github.com/codemirror/codemirror.next/issues/80

**Comment by mootari** [comment]
Again, some feedback would be nice, especially since Observable has announced to phase out Classic within the next 1 1/2 months.

**Comment by CobusT** [comment]
It is a Top N bug which means we are working on it.

**Comment by sydneypalumbo** [comment]
Thanks for continuing to raise this @mootari — it’s an important issue, and we want to provide some more context. From our perspective, there have been two main problems relating to the way in which CodeMirror 6’s editors defer the rendering of off-screen content for performance reasons. The first is that, on some occasions, the editor fails to properly render text that is actually on screen. We filed the [issue](https://github.com/codemirror/codemirror.next/issues/583) linked above in CodeMirror 6’s issue tracker in order to address this, and the author very quickly released a [change](https://github.com/codemirror/view/commit/c72aeb6477ff28f9692d8cd30aa4175e2d8b0890) that will hopefully resolve the specific problem. We’ll have that change pulled into Observable ASAP.

The other issue, which you’ve described above, is that of searching with the browser’s built-in “find” functionality. Because of CodeMirror’s intentional design decision / performance optimization to not render off-screen content in editors, search on the page is inaccurate and often fails to include references to the searched text. CodeMirror does offer [functionality](https://codemirror.net/6/docs/ref/#search) to support searching for values within individual editors, but the challenge in our case is that we need to support searching for values across _all_ editors, rather than just one, so implementing that is a bit less quick / trivial on our end. However, it is something we are considering (and that has other potential benefits like offering a way to find _and_ replace, or search all cells outside of safe mode). The other approach we are considering at the moment is opting out of CodeMirror’s rendering optimization, and we’ve inquired about that on their forum [here](https://discuss.codemirror.net/t/viewport-issues-with-cm-6/3586).

We are actively working on determining the best way to resolve this, know that it is a very frustrating issue in Next, and will update this thread as progress is made towards a solution. Thanks again.

**Comment by mootari** [comment]
@sydneypalumbo Thanks for tackling this issue!

I took another stab at a repro (unsuccessfully) and then went through the Chromium issues, as I've encountered a few instances in notebooks where e.g. ResizeObserver callbacks wouldn't fire at all without restarting Chrome. There appear to be several issues for ResizeObserver and IntersectionObserver that might fit the problem.

If the update issue should persist I'll compile a list of these issues. In the meantime it might be useful to learn wether the problem is limited to Chrome/macOS/Retina (rounding problems seem to be a common theme), or has appeared for other browsers and platforms.

@wiltsecarpenter Re the forum question, could you set [ViewState.printing](https://github.com/codemirror/view/blob/a5d1b45d07c1ebadbbba2fb0963d56d7e8550c23/src/viewstate.ts#L108) to true to force a full render?

**Comment by mootari** [comment]
I just created a local override in Chrome that changed the initialization value for ViewState.printing to `true`. After reloading, a browser search in safe mode now shows 4 results for the notebook / term mentioned in OP, and editing still seems to work as well.

**Comment by mootari** [comment]
Relevant excerpt from CodeMirror's [`beforeprint` handler](https://github.com/codemirror/view/blob/a5d1b45d07c1ebadbbba2fb0963d56d7e8550c23/src/input.ts#L617-L618):
~~~js
  view.viewState.printing = true
  view.requestMeasure()
~~~
As far as I could tell the flag is not set anywhere else, but using this workaround may require to stop native `beforeprint` events so that the handler won't revert `printing` back to false.

**Comment by CobusT** [comment]
Quick update on the two issues:

**Issue 1: Editor sometimes rendering blanks**
We are testing out the fix from Codemirror and hoping that this issue will be resolved soon.

**Issue 2: Lazy rendering causing searching on page to fail**
Thanks for the suggestions... the team is looking into them and trying to assess the consequences of making those changes.

**Comment by mootari** [comment]
@CobusT What's the status on issue 1? I'm still seeing the behavior, so I guess the fix wasn't sufficient?

**Comment by CobusT** [comment]
We have also still seen this happening every now and then (although less often than before) so we still consider this open. We don't have another update at this time.

**Comment by mootari** [comment]
Which other browsers and platforms are affected besides Chrome on macOS?

**Comment by CobusT** [comment]
I see it in Safari every now and then.

**Comment by mootari** [comment]
Observations:
- so far all reports are for macOS
- problem seems to appear only under high GPU load (enable Window > GPU history in macOS Activity Monitor)
- scrolling the page still works, but editor contents don't update - compositing related?
- CodeMirror uses requestAnimationFrame for view.requestMeasure(). Perhaps callback gets cancelled early?

**Comment by CobusT** [comment]
Just a note: We now have a notebook Find and Replace UI. It doesn't close this issue, but it is related enough that I wanted to highlight it here:
https://observablehq.com/@observablehq/release-notes#cell-957

**Comment by mootari** [comment]
@CobusT Any update on issue 2? Find/Replace suffers from the exact same problem - jumping to an offset is not possible due to lazily loaded editor contents (#345).

**Comment by CobusT** [comment]
> @CobusT Any update on issue 2? Find/Replace suffers from the exact same problem - jumping to an offset is not possible due to lazily loaded editor contents (#345).

Sorry no update yet. It is on our hot list though!

**Comment by mootari** [comment]
Here's console snippet to track CodeMirror's changes to the focused editor during lazy loading / unloading:
```javascript
(n => new MutationObserver(() => {
  const line = n => n.matches('.cm-line');
  const height = n => line(n) ? '' : n.style.height;
  console.log([
    height(n.firstChild), 
    Array.from(n.children).filter(line).length,
    height(n.lastChild)
  ]);
}).observe(n, {childList: true}))($('.node-focus .cm-content'))
```
When run, it will log an array at each change consisting of leading spacer height, line count, following spacer height:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/322014/165980825-74911b6e-956d-4775-891c-414a20fe2bfc.png">

**Comment by jrus** [comment]
The notebook find/replace tool is much appreciated! Really great work.

But this code blanking issue continues to be super annoying.

**Comment by CobusT** [comment]
This issue should now be resolved. Please let us know if you see any further issues! 🕺

**Comment by mootari** [comment]
@CobusT Great news! Can you share what the cause turned out to be?

**Comment by CobusT** [comment]
We ended up going with the workaround you suggested, which was to set ViewState.printing to true. We still don't have a way to tell CodeMirror to disable the optimization more elegantly. Which means that if someone actually prints their notebook, this workaround will be disabled for the duration of the time their notebook is loaded.

**Comment by CobusT** [comment]
We ended up going with the workaround you suggested, which was to set ViewState.printing to true. We still don't have a way to tell CodeMirror to disable the optimization more elegantly. Which means that if someone actually prints their notebook, this workaround will be disabled for the duration of the time their notebook is loaded.
